name: MyPaint # you probably want to 'snapcraft register <name>'
version: '1.3.0-Alpha+git' # just for humans, typically '1.2+git' or '1.3.2'
summary: A drawing and painting program that works well with graphics tablets. # 79 char long summary
description: |
  MyPaint is a fast and dead-simple painting app for artists. It works with
  many graphics tablets without any special configuration. You can tweak its
  brushes to work like all kinds of real media. The full-screen mode allows
  you to work without distractions.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  mypaint:
    command: mypaint %f
    desktop: /usr/share/applications/mypaint.desktop
    icon: /mypaint/pixmaps/mypaint_logo.png
    plugs:
      - home
      - mount-observe
      - network
      - network-bind
      - x11

parts:
  libmypaint-git:
    source: https://github.com/mypaint/libmypaint.git
    source-type: git
    plugin: autotools
    build-packages:
      - python2.7
      - intltool
      - gettext
      - libtool
    stage-packages:
      - libjson-c-dev
      - libgirepository1.0-dev
      - libglib2.0-dev

  mypaint-git:
    source: ../
    soruce-type: git
    plugin: nil
    build-packages:
      - swig
      - python-setuptools
      - gettext
      - g++
    stage-packages:
      - python-dev
      - python-numpy
      - libgtk-3-dev
      - python-gi-dev
      - libpng-dev
      - liblcms2-dev
      - libjson-c-dev
      - gir1.2-gtk-3.0
      - python-gi-cairo
    build: |
      python setup.py build
      python setup.py install